/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Add Category */
        post: operations["add_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/db/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_db_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Metrics */
        post: operations["batch_metrics_api_metrics_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/albums/by-spotify/{spotify_album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album By Spotify */
        get: operations["get_album_by_spotify_api_music_albums_by_spotify__spotify_album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album */
        get: operations["get_album_api_music_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/artists/{artist_id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist Albums */
        get: operations["get_artist_albums_api_music_artists__artist_id__albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/search/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spotify 후보 검색(읽기 전용 + 앨범 동기화 enqueue) */
        get: operations["search_candidates_api_music_search_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/search/unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 통합 검색(DB-first) */
        get: operations["unified_search_api_music_search_unified_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_api_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_posts__post_id__get"];
        /** Update Post */
        put: operations["update_post_api_posts__post_id__put"];
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_posts__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restore Post */
        patch: operations["restore_post_api_posts__post_id__restore_patch"];
        trace?: never;
    };
    "/api/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Post */
        post: operations["create_post_api_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCategoryRequest */
        Backend_AddCategoryRequest: {
            /** Name */
            name: string;
        };
        /** CategoryListResponse */
        Backend_CategoryListResponse: {
            /** Categories */
            categories: string[];
        };
        /** CreatePostReq */
        Backend_CreatePostReq: {
            /** Album Cover Url */
            album_cover_url?: string | null;
            /** Album Ids */
            album_ids?: string[];
            /** Artist Ids */
            artist_ids?: string[];
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Post Id */
            post_id?: string | null;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating?: number | null;
            /** Slug */
            slug?: string | null;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        Backend_HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["Backend_ValidationError"][];
        };
        /** MetricsBatchRequest */
        Backend_MetricsBatchRequest: {
            /** Slugs */
            slugs: string[];
        };
        /** MetricsBatchResponse */
        Backend_MetricsBatchResponse: {
            /** Data */
            data: {
                [key: string]: components["schemas"]["Backend_PostMetrics"];
            };
        };
        /** PostDetailResponse */
        Backend_PostDetailResponse: {
            /** Album Ids */
            album_ids: string[];
            /** Artist Ids */
            artist_ids: string[];
            /** Body Mdx */
            body_mdx: string | null;
            /** Category */
            category: string | null;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating: number | null;
            /** Recommended Tracks */
            recommended_tracks?: components["schemas"]["Backend_RecommendedTrackOutput"][];
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** PostListItem */
        Backend_PostListItem: {
            /** Category */
            category?: string | null;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating: number | null;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** PostListResponse */
        Backend_PostListResponse: {
            /** Posts */
            posts: components["schemas"]["Backend_PostListItem"][];
        };
        /** PostMetrics */
        Backend_PostMetrics: {
            /** Comments */
            comments: number;
            /** Likes */
            likes: number;
        };
        /** RecommendedTrackInput */
        Backend_RecommendedTrackInput: {
            /** Album Id */
            album_id: string;
            /** Note */
            note?: string | null;
            /** Position */
            position?: number | null;
            /** Track Id */
            track_id: string;
        };
        /** RecommendedTrackOutput */
        Backend_RecommendedTrackOutput: {
            /** Album Id */
            album_id: string;
            /** Note */
            note?: string | null;
            /** Position */
            position?: number | null;
            /** Track Id */
            track_id: string;
        };
        /** UpdatePostRequest */
        Backend_UpdatePostRequest: {
            /** Album Ids */
            album_ids?: string[] | null;
            /** Artist Ids */
            artist_ids?: string[] | null;
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Posted Date */
            posted_date?: string | null;
            /** Rating */
            rating?: number | null;
            /** Recommended Tracks */
            recommended_tracks?: components["schemas"]["Backend_RecommendedTrackInput"][] | null;
            /** Status */
            status?: ("draft" | "published" | "archived") | null;
            /** Title */
            title?: string | null;
        };
        /** ValidationError */
        Backend_ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WritePostRequest */
        Backend_WritePostRequest: {
            /** Album Classics */
            album_classics?: {
                [key: string]: boolean;
            };
            /** Album Ids */
            album_ids?: string[];
            /** Artist Ids */
            artist_ids?: string[];
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date?: string;
            /** Rating */
            rating?: number | null;
            /** Recommended Tracks */
            recommended_tracks?: components["schemas"]["Backend_RecommendedTrackInput"][];
            /** Search Index */
            search_index?: boolean | null;
            /**
             * Status
             * @default published
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Title */
            title: string;
        };
        /** WritePostResponse */
        Backend_WritePostResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
        };
        /** AlbumDetail */
        Music_AlbumDetail: {
            album: components["schemas"]["Music_AlbumOut"];
            /** Artists */
            artists: components["schemas"]["Music_ArtistOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Tracks */
            tracks: components["schemas"]["Music_TrackOut"][];
        };
        /** AlbumItem */
        Music_AlbumItem: {
            /** Album Type */
            album_type?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Popularity */
            popularity?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Total Tracks */
            total_tracks?: number | null;
        };
        /** AlbumOut */
        Music_AlbumOut: {
            /** Album Type */
            album_type?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
        };
        /** ArtistItem */
        Music_ArtistItem: {
            /** Cover Url */
            cover_url?: string | null;
            /** Followers Count */
            followers_count?: number | null;
            /** Genres */
            genres?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Popularity */
            popularity?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
        };
        /** ArtistOut */
        Music_ArtistOut: {
            /** Followers Count */
            followers_count?: number | null;
            /** Genres */
            genres?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Popularity */
            popularity?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
        };
        /** CandidateAlbumItem */
        Music_CandidateAlbumItem: {
            /** Album Type */
            album_type?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CandidateArtistItem */
        Music_CandidateArtistItem: {
            /** External Url */
            external_url?: string | null;
            /** Genres */
            genres?: string[];
            /** Name */
            name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
        };
        /** CandidatePagination */
        Music_CandidatePagination: {
            /** Href */
            href?: string | null;
            /** Limit */
            limit?: number | null;
            /** Next */
            next?: string | null;
            /** Offset */
            offset?: number | null;
            /** Previous */
            previous?: string | null;
            /** Total */
            total?: number | null;
        };
        /** CandidateSearchResult */
        Music_CandidateSearchResult: {
            /** Albums */
            albums?: components["schemas"]["Music_CandidateAlbumItem"][] | null;
            albums_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
            /** Artists */
            artists?: components["schemas"]["Music_CandidateArtistItem"][] | null;
            artists_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
            /** Tracks */
            tracks?: components["schemas"]["Music_CandidateTrackItem"][] | null;
            tracks_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
        };
        /** CandidateTrackAlbumRef */
        Music_CandidateTrackAlbumRef: {
            /** Cover Url */
            cover_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CandidateTrackItem */
        Music_CandidateTrackItem: {
            album?: components["schemas"]["Music_CandidateTrackAlbumRef"] | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** External Url */
            external_url?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
            /** Track Number */
            track_number?: number | null;
        };
        /** HTTPValidationError */
        Music_HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["Music_ValidationError"][];
        };
        /** SearchResult */
        Music_SearchResult: {
            /** Items */
            items?: (components["schemas"]["Music_ArtistItem"] | components["schemas"]["Music_AlbumItem"])[];
            /** Type */
            type: string;
        };
        /** TrackItem */
        Music_TrackItem: {
            /** Album Id */
            album_id: string;
            /** Album Spotify Id */
            album_spotify_id?: string | null;
            /** Album Title */
            album_title?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Id */
            id: string;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Track No */
            track_no?: number | null;
        };
        /** TrackOut */
        Music_TrackOut: {
            /** Duration Sec */
            duration_sec?: number | null;
            /** Feat Artist Names */
            feat_artist_names?: string[];
            /** Id */
            id: string;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Track No */
            track_no?: number | null;
        };
        /** UnifiedSearchResult */
        Music_UnifiedSearchResult: {
            /** Albums */
            albums?: components["schemas"]["Music_AlbumItem"][];
            /** Artists */
            artists?: components["schemas"]["Music_ArtistItem"][];
            /** Tracks */
            tracks?: components["schemas"]["Music_TrackItem"][];
        };
        /** ValidationError */
        Music_ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_CategoryListResponse"];
                };
            };
        };
    };
    add_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_AddCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    ping_api_db_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    batch_metrics_api_metrics_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_MetricsBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_MetricsBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    get_album_by_spotify_api_music_albums_by_spotify__spotify_album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_album_api_music_albums__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_artist_albums_api_music_artists__artist_id__albums_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    search_candidates_api_music_search_candidates_get: {
        parameters: {
            query: {
                /** @description Spotify 검색 쿼리 */
                q: string;
                /** @description 허용: "album,artist,track" 중 조합 */
                type?: string;
                /** @description 예: KR, US */
                market?: string | null;
                limit?: number;
                offset?: number;
                /** @description 선택값: "audio" */
                include_external?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_CandidateSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    unified_search_api_music_search_unified_get: {
        parameters: {
            query: {
                /** @description 검색어 */
                q: string;
                /** @description 검색 대상 (콤마 조합 허용): "album", "artist", "track" */
                type?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_UnifiedSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    list_posts_api_posts_get: {
        parameters: {
            query?: {
                status?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_PostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_WritePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_WritePostResponse"];
                };
            };
            /** @description Slug derived from title already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_PostDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_posts__post_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_UpdatePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_WritePostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_posts__post_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-archived (status='archived'); body echoes new status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Hard-deleted; no body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    restore_post_api_posts__post_id__restore_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_CreatePostReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
