/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/buckets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buckets */
        get: operations["list_buckets_api_buckets_get"];
        put?: never;
        /** Create Bucket */
        post: operations["create_bucket_api_buckets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder */
        put: operations["reorder_api_buckets_reorder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Bucket */
        delete: operations["delete_bucket_api_buckets__bucket_id__delete"];
        options?: never;
        head?: never;
        /** Update Bucket */
        patch: operations["update_bucket_api_buckets__bucket_id__patch"];
        trace?: never;
    };
    "/api/buckets/{bucket_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Item */
        post: operations["add_item_api_buckets__bucket_id__items_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/buckets/{bucket_id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Item */
        delete: operations["delete_item_api_buckets__bucket_id__items__item_id__delete"];
        options?: never;
        head?: never;
        /** Update Item */
        patch: operations["update_item_api_buckets__bucket_id__items__item_id__patch"];
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        /** Add Category */
        post: operations["add_category_api_categories_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/db/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: operations["ping_api_db_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/reviewed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviewed */
        get: operations["list_reviewed_api_library_reviewed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/to-listen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List To Listen */
        get: operations["list_to_listen_api_library_to_listen_get"];
        put?: never;
        /** Add To Listen */
        post: operations["add_to_listen_api_library_to_listen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/to-listen/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder To Listen */
        put: operations["reorder_to_listen_api_library_to_listen_reorder_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/to-listen/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete To Listen */
        delete: operations["delete_to_listen_api_library_to_listen__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Metrics */
        post: operations["batch_metrics_api_metrics_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/albums/by-spotify/{spotify_album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album By Spotify */
        get: operations["get_album_by_spotify_api_music_albums_by_spotify__spotify_album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/albums/{album_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Album */
        get: operations["get_album_api_music_albums__album_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/artists/by-spotify/{spotify_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist By Spotify */
        get: operations["get_artist_by_spotify_api_music_artists_by_spotify__spotify_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/artists/{artist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist */
        get: operations["get_artist_api_music_artists__artist_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/artists/{artist_id}/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist Albums */
        get: operations["get_artist_albums_api_music_artists__artist_id__albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/artists/{artist_id}/top-tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Artist Top Tracks */
        get: operations["get_artist_top_tracks_api_music_artists__artist_id__top_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/search/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spotify 후보 검색(읽기 전용 + 앨범 동기화 enqueue) */
        get: operations["search_candidates_api_music_search_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/music/search/unified": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 통합 검색(DB-first) */
        get: operations["unified_search_api_music_search_unified_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Posts */
        get: operations["list_posts_api_posts_get"];
        put?: never;
        /** Create Post */
        post: operations["create_post_api_posts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Post */
        get: operations["get_post_api_posts__post_id__get"];
        /** Update Post */
        put: operations["update_post_api_posts__post_id__put"];
        post?: never;
        /** Delete Post */
        delete: operations["delete_post_api_posts__post_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/posts/{post_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Restore Post */
        patch: operations["restore_post_api_posts__post_id__restore_patch"];
        trace?: never;
    };
    "/api/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Post */
        post: operations["create_post_api_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddBucketItemRequest */
        Backend_AddBucketItemRequest: {
            /** Album Id */
            album_id: string;
            /** Note */
            note?: string | null;
        };
        /** AddCategoryRequest */
        Backend_AddCategoryRequest: {
            /** Name */
            name: string;
        };
        /** AddToListenRequest */
        Backend_AddToListenRequest: {
            /** Album Id */
            album_id: string;
            /** Note */
            note?: string | null;
        };
        /** AlbumBrief */
        Backend_AlbumBrief: {
            /** Artist Names */
            artist_names?: string[];
            /** Cover Url */
            cover_url?: string | null;
            /** Id */
            id: string;
            /** Popularity */
            popularity?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Title */
            title: string;
        };
        /** BucketItemResponse */
        Backend_BucketItemResponse: {
            album: components["schemas"]["Backend_AlbumBrief"];
            /** Album Id */
            album_id: string;
            /**
             * Already Reviewed
             * @default false
             */
            already_reviewed: boolean;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /** Position */
            position: number;
            /** Post Id */
            post_id?: string | null;
            /** Rec Reason */
            rec_reason?: string | null;
            /** Status */
            status: string;
        };
        /** BucketResponse */
        Backend_BucketResponse: {
            /** Color */
            color?: string | null;
            /** Id */
            id: string;
            /** Is Done */
            is_done: boolean;
            /** Items */
            items?: components["schemas"]["Backend_BucketItemResponse"][];
            /** Name */
            name: string;
            /** Position */
            position: number;
        };
        /** BucketsResponse */
        Backend_BucketsResponse: {
            /** Buckets */
            buckets?: components["schemas"]["Backend_BucketResponse"][];
        };
        /** CategoryListResponse */
        Backend_CategoryListResponse: {
            /** Categories */
            categories: string[];
        };
        /** CreateBucketRequest */
        Backend_CreateBucketRequest: {
            /** Color */
            color?: string | null;
            /** Name */
            name: string;
        };
        /** CreatePostReq */
        Backend_CreatePostReq: {
            /** Album Cover Url */
            album_cover_url?: string | null;
            /** Album Ids */
            album_ids?: string[];
            /** Artist Ids */
            artist_ids?: string[];
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /** Post Id */
            post_id?: string | null;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating?: number | null;
            /** Recommended Track Ids */
            recommended_track_ids?: string[];
            /** Slug */
            slug?: string | null;
            /** Title */
            title: string;
        };
        /** HTTPValidationError */
        Backend_HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["Backend_ValidationError"][];
        };
        /** MetricsBatchRequest */
        Backend_MetricsBatchRequest: {
            /** Slugs */
            slugs: string[];
        };
        /** MetricsBatchResponse */
        Backend_MetricsBatchResponse: {
            /** Data */
            data: {
                [key: string]: components["schemas"]["Backend_PostMetrics"];
            };
        };
        /** PostDetailResponse */
        Backend_PostDetailResponse: {
            /** Album Ids */
            album_ids: string[];
            /** Artist Ids */
            artist_ids: string[];
            /** Body Mdx */
            body_mdx: string | null;
            /** Category */
            category: string | null;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating: number | null;
            /** Recommended Track Ids */
            recommended_track_ids?: string[];
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Subject Best New */
            subject_best_new?: boolean | null;
            /** Title */
            title: string;
        };
        /** PostListItem */
        Backend_PostListItem: {
            /** Category */
            category?: string | null;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date: string;
            /** Rating */
            rating: number | null;
            /** Slug */
            slug: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** PostListResponse */
        Backend_PostListResponse: {
            /** Posts */
            posts: components["schemas"]["Backend_PostListItem"][];
        };
        /** PostMetrics */
        Backend_PostMetrics: {
            /** Comments */
            comments: number;
            /** Likes */
            likes: number;
        };
        /** ReorderBucket */
        Backend_ReorderBucket: {
            /** Id */
            id: string;
            /** Item Ids */
            item_ids?: string[];
        };
        /** ReorderRequest */
        Backend_ReorderRequest: {
            /** Buckets */
            buckets?: components["schemas"]["Backend_ReorderBucket"][];
        };
        /** ReviewedAlbumResponse */
        Backend_ReviewedAlbumResponse: {
            album: components["schemas"]["Backend_AlbumBrief"];
            /** Album Id */
            album_id: string;
            /** Review Ids */
            review_ids?: string[];
        };
        /** ReviewedResponse */
        Backend_ReviewedResponse: {
            /** Items */
            items?: components["schemas"]["Backend_ReviewedAlbumResponse"][];
        };
        /** ToListenItemResponse */
        Backend_ToListenItemResponse: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            album: components["schemas"]["Backend_AlbumBrief"];
            /** Album Id */
            album_id: string;
            /** Id */
            id: string;
            /** Note */
            note?: string | null;
            /** Position */
            position: number;
        };
        /** ToListenReorderRequest */
        Backend_ToListenReorderRequest: {
            /** Item Ids */
            item_ids?: string[];
        };
        /** ToListenResponse */
        Backend_ToListenResponse: {
            /** Items */
            items?: components["schemas"]["Backend_ToListenItemResponse"][];
        };
        /** UpdateBucketItemRequest */
        Backend_UpdateBucketItemRequest: {
            /** Note */
            note?: string | null;
            /** Post Id */
            post_id?: string | null;
            /** Status */
            status?: ("candidate" | "drafting" | "published") | null;
        };
        /** UpdateBucketRequest */
        Backend_UpdateBucketRequest: {
            /** Color */
            color?: string | null;
            /** Is Done */
            is_done?: boolean | null;
            /** Name */
            name?: string | null;
            /** Position */
            position?: number | null;
        };
        /** UpdatePostRequest */
        Backend_UpdatePostRequest: {
            /** Album Ids */
            album_ids?: string[] | null;
            /** Artist Ids */
            artist_ids?: string[] | null;
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /** Description */
            description?: string | null;
            /** Posted Date */
            posted_date?: string | null;
            /** Rating */
            rating?: number | null;
            /** Recommended Track Ids */
            recommended_track_ids?: string[] | null;
            /** Status */
            status?: ("draft" | "published" | "archived") | null;
            /** Subject Best New */
            subject_best_new?: boolean | null;
            /** Title */
            title?: string | null;
        };
        /** ValidationError */
        Backend_ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WritePostRequest */
        Backend_WritePostRequest: {
            /** Album Classics */
            album_classics?: {
                [key: string]: boolean;
            };
            /** Album Ids */
            album_ids?: string[];
            /** Artist Ids */
            artist_ids?: string[];
            /** Body Mdx */
            body_mdx?: string | null;
            /** Category */
            category?: string | null;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Posted Date
             * Format: date
             */
            posted_date?: string;
            /** Rating */
            rating?: number | null;
            /** Recommended Track Ids */
            recommended_track_ids?: string[];
            /** Search Index */
            search_index?: boolean | null;
            /**
             * Status
             * @default published
             * @enum {string}
             */
            status: "draft" | "published" | "archived";
            /** Subject Best New */
            subject_best_new?: boolean | null;
            /** Title */
            title: string;
        };
        /** WritePostResponse */
        Backend_WritePostResponse: {
            /** Id */
            id: string;
            /** Slug */
            slug: string;
        };
        /** AlbumDetail */
        Music_AlbumDetail: {
            album: components["schemas"]["Music_AlbumOut"];
            /** Artists */
            artists: components["schemas"]["Music_ArtistOut"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
            /** Tracks */
            tracks: components["schemas"]["Music_TrackOut"][];
        };
        /** AlbumItem */
        Music_AlbumItem: {
            /** Album Type */
            album_type?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /**
             * Best New
             * @default false
             */
            best_new: boolean;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Popularity */
            popularity?: number | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Total Tracks */
            total_tracks?: number | null;
        };
        /** AlbumOut */
        Music_AlbumOut: {
            /** Album Type */
            album_type?: string | null;
            /**
             * Best New
             * @default false
             */
            best_new: boolean;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
        };
        /** ArtistHero */
        Music_ArtistHero: {
            /**
             * Album Count
             * @default 0
             */
            album_count: number;
            /** Followers */
            followers?: number | null;
            /** Genres */
            genres?: string[];
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Popularity */
            popularity?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
            /**
             * Status
             * @default ready
             */
            status: string;
            /**
             * Track Count
             * @default 0
             */
            track_count: number;
        };
        /** ArtistItem */
        Music_ArtistItem: {
            /** Cover Url */
            cover_url?: string | null;
            /** Followers Count */
            followers_count?: number | null;
            /** Genres */
            genres?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Popularity */
            popularity?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
        };
        /** ArtistOut */
        Music_ArtistOut: {
            /** Followers Count */
            followers_count?: number | null;
            /** Genres */
            genres?: string[];
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Photo Url */
            photo_url?: string | null;
            /** Popularity */
            popularity?: number | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Spotify Url */
            spotify_url?: string | null;
        };
        /** CandidateAlbumItem */
        Music_CandidateAlbumItem: {
            /** Album Type */
            album_type?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** External Url */
            external_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CandidateArtistItem */
        Music_CandidateArtistItem: {
            /** External Url */
            external_url?: string | null;
            /** Genres */
            genres?: string[];
            /** Name */
            name?: string | null;
            /** Photo Url */
            photo_url?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
        };
        /** CandidatePagination */
        Music_CandidatePagination: {
            /** Href */
            href?: string | null;
            /** Limit */
            limit?: number | null;
            /** Next */
            next?: string | null;
            /** Offset */
            offset?: number | null;
            /** Previous */
            previous?: string | null;
            /** Total */
            total?: number | null;
        };
        /** CandidateSearchResult */
        Music_CandidateSearchResult: {
            /** Albums */
            albums?: components["schemas"]["Music_CandidateAlbumItem"][] | null;
            albums_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
            /** Artists */
            artists?: components["schemas"]["Music_CandidateArtistItem"][] | null;
            artists_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
            /** Tracks */
            tracks?: components["schemas"]["Music_CandidateTrackItem"][] | null;
            tracks_pagination?: components["schemas"]["Music_CandidatePagination"] | null;
        };
        /** CandidateTrackAlbumRef */
        Music_CandidateTrackAlbumRef: {
            /** Cover Url */
            cover_url?: string | null;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
        };
        /** CandidateTrackItem */
        Music_CandidateTrackItem: {
            album?: components["schemas"]["Music_CandidateTrackAlbumRef"] | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Artist Spotify Id */
            artist_spotify_id?: string | null;
            /** Duration Ms */
            duration_ms?: number | null;
            /** External Url */
            external_url?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title?: string | null;
            /** Track Number */
            track_number?: number | null;
        };
        /** HTTPValidationError */
        Music_HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["Music_ValidationError"][];
        };
        /** SearchResult */
        Music_SearchResult: {
            /** Items */
            items?: (components["schemas"]["Music_ArtistItem"] | components["schemas"]["Music_AlbumItem"])[];
            /** Type */
            type: string;
        };
        /** TrackItem */
        Music_TrackItem: {
            /** Album Id */
            album_id: string;
            /** Album Spotify Id */
            album_spotify_id?: string | null;
            /** Album Title */
            album_title?: string | null;
            /** Artist Name */
            artist_name?: string | null;
            /** Cover Url */
            cover_url?: string | null;
            /** Duration Sec */
            duration_sec?: number | null;
            /** Feat Artist Names */
            feat_artist_names?: string[];
            /** Id */
            id: string;
            /** Release Date */
            release_date?: string | null;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Track No */
            track_no?: number | null;
        };
        /** TrackOut */
        Music_TrackOut: {
            /** Duration Sec */
            duration_sec?: number | null;
            /** Feat Artist Names */
            feat_artist_names?: string[];
            /** Id */
            id: string;
            /** Spotify Id */
            spotify_id?: string | null;
            /** Title */
            title: string;
            /** Track No */
            track_no?: number | null;
        };
        /** UnifiedSearchResult */
        Music_UnifiedSearchResult: {
            /** Albums */
            albums?: components["schemas"]["Music_AlbumItem"][];
            /** Artists */
            artists?: components["schemas"]["Music_ArtistItem"][];
            /** Tracks */
            tracks?: components["schemas"]["Music_TrackItem"][];
        };
        /** ValidationError */
        Music_ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_buckets_api_buckets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_BucketsResponse"];
                };
            };
        };
    };
    create_bucket_api_buckets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_CreateBucketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_BucketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    reorder_api_buckets_reorder_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_ReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    delete_bucket_api_buckets__bucket_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    update_bucket_api_buckets__bucket_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_UpdateBucketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_BucketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    add_item_api_buckets__bucket_id__items_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_AddBucketItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_BucketItemResponse"];
                };
            };
            /** @description Album already in this bucket */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    delete_item_api_buckets__bucket_id__items__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    update_item_api_buckets__bucket_id__items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bucket_id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_UpdateBucketItemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_BucketItemResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_CategoryListResponse"];
                };
            };
        };
    };
    add_category_api_categories_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_AddCategoryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    ping_api_db_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_reviewed_api_library_reviewed_get: {
        parameters: {
            query?: {
                group_by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_ReviewedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    list_to_listen_api_library_to_listen_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_ToListenResponse"];
                };
            };
        };
    };
    add_to_listen_api_library_to_listen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_AddToListenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_ToListenItemResponse"];
                };
            };
            /** @description Album already in the to-listen queue */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    reorder_to_listen_api_library_to_listen_reorder_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_ToListenReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    delete_to_listen_api_library_to_listen__item_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    batch_metrics_api_metrics_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_MetricsBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_MetricsBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    get_album_by_spotify_api_music_albums_by_spotify__spotify_album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_album_api_music_albums__album_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                album_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_AlbumDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_artist_by_spotify_api_music_artists_by_spotify__spotify_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spotify_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_ArtistHero"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_artist_api_music_artists__artist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_ArtistHero"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_artist_albums_api_music_artists__artist_id__albums_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_SearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    get_artist_top_tracks_api_music_artists__artist_id__top_tracks_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                artist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_TrackItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    search_candidates_api_music_search_candidates_get: {
        parameters: {
            query: {
                /** @description Spotify 검색 쿼리 */
                q: string;
                /** @description 허용: "album,artist,track" 중 조합 */
                type?: string;
                /** @description 예: KR, US */
                market?: string | null;
                limit?: number;
                offset?: number;
                /** @description 선택값: "audio" */
                include_external?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_CandidateSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    unified_search_api_music_search_unified_get: {
        parameters: {
            query: {
                /** @description 검색어 */
                q: string;
                /** @description 검색 대상 (콤마 조합 허용): "album", "artist", "track" */
                type?: string;
                limit?: number;
                /** @description Fallback offset applied to any bucket without an explicit override. */
                offset?: number;
                /** @description Per-bucket offset for the artists slice (overrides `offset`). */
                artist_offset?: number | null;
                /** @description Per-bucket offset for the albums slice (overrides `offset`). */
                album_offset?: number | null;
                /** @description Per-bucket offset for the tracks slice (overrides `offset`). */
                track_offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_UnifiedSearchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Music_HTTPValidationError"];
                };
            };
        };
    };
    list_posts_api_posts_get: {
        parameters: {
            query?: {
                status?: string | null;
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_PostListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_posts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_WritePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_WritePostResponse"];
                };
            };
            /** @description Slug derived from title already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    get_post_api_posts__post_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_PostDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    update_post_api_posts__post_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_UpdatePostRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_WritePostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    delete_post_api_posts__post_id__delete: {
        parameters: {
            query?: {
                hard?: boolean;
            };
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-archived (status='archived'); body echoes new status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Hard-deleted; no body. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Post not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    restore_post_api_posts__post_id__restore_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                post_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    create_post_api_publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Backend_CreatePostReq"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Backend_HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
